type User{
    id: ID!
    name: String!
    bio: String!
    projects: [Project!]!
}

type Project{
    name: String!
    owner: User!
    contributors: [User!]! 
    contributor(name: String!): User
}

type Query{
    hello: String
    projects: [Project!]!
    project(name: String!): Project
}